# -*- coding: utf-8 -*-
"""tas_kagit_makas_AYHAN_ASIK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT1-ME2_jtk-E2EHW31g4PX6pAXqiTHx
"""

def tas_kagit_makas_AYHAN_ASIK():
  import random
  # Hoşgeldin ekranı
  print("+--------------------------------------------+")
  print("!                                            !")
  print("!  Taş - Kağıt - Makas Oyununa Hoş Geldiniz  !")
  print("!                                            !")
  print("!                         v1.0 / Ayhan Aşık  !")
  print("!                                            !")
  print("+--------------------------------------------+")
  secim = input("Devam etmek için E veya e giriniz.")

  if(secim == 'E' or secim == 'e'):
    # Bilgilendirme ekranı
    print("+------------------------------------------------------------------------------------+")
    print("!                                                                                    !")
    print("!  Bu oyunda sizin ve bilgisayarın yaptığı seçimde kazanan tarafa bir puan verilir.  !")
    print("!  Toplamda 2 puan toplayan kazanmış olur. İki oyuncuya da yeni tur isteği sorulur.  !")
    print("!  Alınan cevaba göre ya yeni bir oyun başlatılır yada vazgeçilir.                   !")
    print("!                                                                                    !")
    print("+------------------------------------------------------------------------------------+")

    secim = input("Oyuna başlamak istiyorsanız E veya e giriniz")

    if(secim == 'E' or secim == 'e'):
      # ilgili tanımlar yapılıyor.
      secenekler = ['Taş','Kağıt','Makas']
      evet_hayir = ['E','H']
      oyun_sayisi = 1
      tur_sayisi = 1
      beraberlik_sayisi = 0
      oyuncu_kazandi = 0
      oyuncu_kazandi_toplam = 0
      bilgisayar_kazandi = 0
      bilgisayar_kazandi_toplam = 0
      # Oyun başlıyor.
      while True:
        print(f"\n{oyun_sayisi}. OYUN - {tur_sayisi}. TUR")
        print("===========================================")
        if (oyun_sayisi == 1 and tur_sayisi == 1):
          print("\nHaydi Bismillah. İlk seçim senin sonra bilgisayarın.")
          print("\nTaş seçmek istiyorsanız   : T")
          print("Kağıt seçmek istiyorsanız : K")
          print("Makas seçmek istiyorsanız : M")
          print("Oyundan çıkmak  için      : X giriniz...")

        # seçimler toplanıyor
        print("")
        oyuncunun_secimi = input("Seçiminiz   T/K/M veya X : ")
        oyuncunun_secimi = oyuncunun_secimi.upper()
        bilgisayarin_secimi = random.choice(secenekler)
        # kazanan belirleniyor ve sayacı artırılıyor.
        if (oyuncunun_secimi == 'T' or oyuncunun_secimi == 'K' or oyuncunun_secimi == 'M'):
          print(f"Bilgisayarın seçimi      : {bilgisayarin_secimi[0]}")
          if (oyuncunun_secimi == bilgisayarin_secimi[0]):
            beraberlik_sayisi = beraberlik_sayisi + 1
            print("\n==> Bu turda kazanan çıkmadı. BERABERLİK!")
          elif((oyuncunun_secimi == 'T' and bilgisayarin_secimi[0] == 'M')
          or (oyuncunun_secimi == 'K' and bilgisayarin_secimi[0] == 'T')
          or (oyuncunun_secimi == 'M' and bilgisayarin_secimi[0] == 'K')):
            oyuncu_kazandi = oyuncu_kazandi + 1
            print("\n==> Bu turda kazanan SENSİN. Yaşasın!")
          else:
            bilgisayar_kazandi = bilgisayar_kazandi + 1
            print("\n==> Bu turda kazanan bilgisayar.")

          # oyun kazanma şartı sağlandıysa
          if (oyuncu_kazandi == 2):
            oyuncu_kazandi_toplam = oyuncu_kazandi_toplam + 1
            print("+----------------------------+")
            print("!                            !")
            print(f"!  {oyun_sayisi}. oyunun galibi SENSİN!  !")
            print("!                            !")
            print("+----------------------------+")
            yeni_oyun_secimi = input("\nYeni bir oyun için E veya e giriniz.")
            # yeni oyun oynamak istendiğinde
            if (yeni_oyun_secimi == 'E' or yeni_oyun_secimi == 'e'):
              bilgisayar_yeni_oyun_secimi = random.choice(evet_hayir)
              if (bilgisayar_yeni_oyun_secimi == 'E'):
                oyuncu_kazandi = 0
                oyun_sayisi = oyun_sayisi + 1
                tur_sayisi = 1
              else:
                print("\nBilgisayar oynamak istemiyor. Teşekkürler.")
                ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam)
                break
            else:
              ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam)
              break
          elif(bilgisayar_kazandi == 2):
            bilgisayar_kazandi_toplam = bilgisayar_kazandi_toplam + 1
            print("+--------------------------------+")
            print("!                                !")
            print(f"!  {oyun_sayisi}. oyunun galibi BİLGİSAYAR!  !")
            print("!                                !")
            print("+--------------------------------+")
            yeni_oyun_secimi = input("\nYeni bir oyun için E veya e giriniz.")
            # yeni oyun oynamak istendiğinde
            if (yeni_oyun_secimi == 'E' or yeni_oyun_secimi == 'e'):
              bilgisayar_yeni_oyun_secimi = random.choice(evet_hayir)
              if (bilgisayar_yeni_oyun_secimi == 'E'):
                bilgisayar_kazandi = 0
                oyun_sayisi = oyun_sayisi + 1
                tur_sayisi = 1
              else:
                print("\nBilgisayar oynamak istemiyor. Teşekkürler.")
                ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam)
                break
            else:
              ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam)
              break
          else:
            tur_sayisi = tur_sayisi + 1

        # oyuncu çıkış isteğinde bulunursa
        elif(oyuncunun_secimi == 'X' or oyuncunun_secimi == 'x'):
          ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam)
          break
        else:
          print("\n***  HATALI SEÇİM YAPTINIZ!  ***")
      # while sonu
    else:
      print("\n***   Yine gel. Güle güle! :)   ***")
  else:
    print("\n>>>   Bir gün oynarız inşallah! :(   <<<")

def ozet(oyuncu_kazandi_toplam, bilgisayar_kazandi_toplam):
  print("\n*******    OYUN ÖZETİ    *******")
  print(f"\nOyuncunun kazandığı oyun    : {oyuncu_kazandi_toplam}")
  print(f"Bilgisayarın kazandığı oyun : {bilgisayar_kazandi_toplam}")
  print("\n*******    Başarılar!    *******")

tas_kagit_makas_AYHAN_ASIK()

